"""
AI Content Detection Module

Uses heuristic/statistical methods (no external APIs) to estimate the
probability that a piece of text was generated by an AI language model.

Techniques used:
  - Perplexity proxy via word-frequency analysis
  - Burstiness analysis (sentence-length variation)
  - Common AI phrase / pattern detection
  - Vocabulary richness (type-token ratio)
"""

import re
import math
import string
from collections import Counter

# ---------------------------------------------------------------------------
# Common AI-generated phrase patterns (case-insensitive)
# ---------------------------------------------------------------------------
AI_PHRASES = [
    r"\bin conclusion\b",
    r"\bto summarize\b",
    r"\bit is important to note\b",
    r"\bit is worth noting\b",
    r"\bit is essential to\b",
    r"\bit is crucial to\b",
    r"\bfurthermore\b",
    r"\bmoreover\b",
    r"\badditionally\b",
    r"\bin summary\b",
    r"\boverall\b",
    r"\bin today's (world|society|digital age)\b",
    r"\bthe importance of\b",
    r"\bplays a (crucial|vital|important|key|significant) role\b",
    r"\bin this (essay|article|paper|post|piece)\b",
    r"\bultimately\b",
    r"\bin the realm of\b",
    r"\bembark on a journey\b",
    r"\bdelve into\b",
    r"\bfostering\b",
    r"\bnavigating the (complexities|landscape|world)\b",
    r"\bseamlessly\b",
    r"\brobust\b",
    r"\btailored to\b",
    r"\beveryone's (unique )?needs\b",
    r"\bit's worth (mentioning|noting|pointing out)\b",
]

AI_PHRASE_PATTERNS = [re.compile(p, re.IGNORECASE) for p in AI_PHRASES]


def _tokenize_sentences(text):
    """Split text into sentences using basic punctuation rules."""
    raw = re.split(r'(?<=[.!?])\s+', text.strip())
    return [s for s in raw if s.strip()]


def _tokenize_words(text):
    """Return lowercase words (letters only)."""
    return re.findall(r"[a-z']+", text.lower())


def _perplexity_score(text):
    """
    Proxy perplexity: use unigram log-probability over the text itself.
    Highly repetitive text → lower entropy → higher AI probability.
    Returns a value 0-100 where higher = more likely AI.
    """
    words = _tokenize_words(text)
    if len(words) < 20:
        return 50.0

    counts = Counter(words)
    total = sum(counts.values())
    entropy = -sum(
        (c / total) * math.log2(c / total)
        for c in counts.values()
    )

    # Typical human text has high entropy; AI text tends to be more predictable.
    # Empirically calibrated: entropy ~10-12 is normal human, <8 suggests AI.
    # Map entropy to 0-100 AI probability (inverse relationship).
    max_entropy = math.log2(len(counts)) if len(counts) > 1 else 1
    # Normalise to [0,1] then invert
    norm = min(entropy / max(max_entropy, 1), 1.0)
    ai_prob = (1.0 - norm) * 100
    return round(ai_prob, 2)


def _burstiness_score(text):
    """
    Burstiness: human writing has high variance in sentence length.
    AI writing tends toward uniform sentence lengths.
    Returns 0-100 where higher = more likely AI (low burstiness).
    """
    sentences = _tokenize_sentences(text)
    if len(sentences) < 3:
        return 50.0

    lengths = [len(s.split()) for s in sentences]
    mean = sum(lengths) / len(lengths)
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    std = math.sqrt(variance)

    # coefficient of variation: higher = more human
    cv = std / mean if mean > 0 else 0
    # Typical human: cv > 0.4; AI: cv < 0.2
    ai_prob = max(0.0, min(100.0, (0.5 - cv) * 200))
    return round(ai_prob, 2)


def _phrase_score(text):
    """
    Count how many common AI phrases appear per 1000 words.
    Returns 0-100 AI probability.
    """
    words = _tokenize_words(text)
    word_count = max(len(words), 1)
    hits = sum(1 for p in AI_PHRASE_PATTERNS if p.search(text))
    density = (hits / word_count) * 1000
    # >5 hits per 1000 words is very suspicious
    ai_prob = min(100.0, density * 20)
    return round(ai_prob, 2)


def _vocabulary_richness_score(text):
    """
    Type-token ratio (TTR): unique words / total words.
    Low TTR → repetitive → AI.  Returns 0-100 AI probability.
    """
    words = _tokenize_words(text)
    if len(words) < 20:
        return 50.0
    ttr = len(set(words)) / len(words)
    # Human writing: TTR ~0.4-0.7; AI text can be lower
    # Map TTR to AI probability
    ai_prob = max(0.0, min(100.0, (0.6 - ttr) * 200))
    return round(ai_prob, 2)


def _repetition_score(text):
    """
    Check for repeated phrases (3+ word n-grams repeated multiple times).
    Returns 0-100 AI probability.
    """
    words = _tokenize_words(text)
    if len(words) < 30:
        return 0.0

    trigrams = [' '.join(words[i:i+3]) for i in range(len(words) - 2)]
    counts = Counter(trigrams)
    repeated = sum(1 for c in counts.values() if c > 2)
    density = repeated / max(len(trigrams), 1)
    ai_prob = min(100.0, density * 500)
    return round(ai_prob, 2)


def detect_ai_content(text, threshold=55.0):
    """
    Analyse a chunk of text and return:
      {
        'ai_score': float,          # 0-100 overall probability
        'is_ai_flagged': bool,
        'details': {
            'perplexity': float,
            'burstiness': float,
            'phrase': float,
            'vocabulary': float,
            'repetition': float,
        }
      }
    """
    if not text or not text.strip():
        return {'ai_score': 0.0, 'is_ai_flagged': False, 'details': {}}

    perplexity = _perplexity_score(text)
    burstiness = _burstiness_score(text)
    phrase = _phrase_score(text)
    vocabulary = _vocabulary_richness_score(text)
    repetition = _repetition_score(text)

    # Weighted average (phrase density and burstiness weighted more heavily)
    ai_score = (
        perplexity * 0.15
        + burstiness * 0.25
        + phrase * 0.30
        + vocabulary * 0.15
        + repetition * 0.15
    )
    ai_score = round(min(100.0, max(0.0, ai_score)), 2)

    return {
        'ai_score': ai_score,
        'is_ai_flagged': ai_score >= threshold,
        'details': {
            'perplexity': perplexity,
            'burstiness': burstiness,
            'phrase': phrase,
            'vocabulary': vocabulary,
            'repetition': repetition,
        }
    }


def analyse_document(chunks, threshold=55.0):
    """
    Analyse a list of text chunks.
    Returns overall AI percentage and per-chunk results.
    """
    results = []
    for i, chunk in enumerate(chunks):
        result = detect_ai_content(chunk, threshold)
        result['chunk_index'] = i
        results.append(result)

    if not results:
        return {'overall_ai_percentage': 0.0, 'chunk_results': []}

    avg_score = sum(r['ai_score'] for r in results) / len(results)
    return {
        'overall_ai_percentage': round(avg_score, 2),
        'chunk_results': results,
    }
